# Generated by Django 2.1.7 on 2019-03-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_create', models.IntegerField()),
                ('market_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Beers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_id', models.IntegerField()),
                ('label', models.CharField(max_length=60)),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('descripton', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Markets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('basket_id', models.IntegerField()),
                ('markert_id', models.IntegerField()),
                ('beer_id', models.IntegerField()),
                ('price', models.FloatField()),
                ('price_liter', models.FloatField()),
            ],
        ),
    ]
